site_name: pytest-case Docs
repo_url: https://github.com/eitanwass/pytest-case
nav:
  - Home: index.md
  - API reference: api_reference.md
theme: readthedocs
plugins:
  - mkdocstrings:
      handlers: 
        python:
          options:
            docstring_style: google
            show_signature_annotations: true
            separate_signature: true
            show_root_heading: true
