name: pytest-case CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    types: 
      - opened
      - edited

permissions:
  contents: read

jobs:
  Lint:
    name: Run lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Lint with Ruff
        run: |
          poetry run ruff check
  
  Test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Run tests
        run: poetry run pytest --cov --cov-report=xml --junitxml=junit.xml -o junit_family=legacy
      - name: Upload coverage results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload tests results to Codecov
        uses: codecov/test-results-action@v1
        with:
          token: ${{secrets.CODECOV_TOKEN}}
